var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(g,p,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");g!=Array.prototype&&g!=Object.prototype&&(g[p]=c.value)};$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(g){return $jscomp.SYMBOL_PREFIX+(g||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var g=$jscomp.global.Symbol.iterator;g||(g=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[g]&&$jscomp.defineProperty(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(g){var p=0;return $jscomp.iteratorPrototype(function(){return p<g.length?{done:!1,value:g[p++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(g){$jscomp.initSymbolIterator();g={next:g};g[$jscomp.global.Symbol.iterator]=function(){return this};return g};$jscomp.makeIterator=function(g){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var p=g[Symbol.iterator];return p?p.call(g):$jscomp.arrayIterator(g)};$jscomp.arrayFromIterator=function(g){for(var p,c=[];!(p=g.next()).done;)c.push(p.value);return c};$jscomp.arrayFromIterable=function(g){return g instanceof Array?g:$jscomp.arrayFromIterator($jscomp.makeIterator(g))};
(function(){function g(d,c,b){d.every(function(a){return a.name!==c})&&d.push({name:c,shallow:b})}function p(d,c){for(var b=[];d!==c;)d.type===K&&g(b,d.name,d.shallow),d.type===L?(d.next.forEach(function(a){return a.props.forEach(function(a){return g(b,a.name,a.shallow)})}),d=d.end):d.type!==M&&d.type!==N&&d.type!==I||!d.props?d=d.next:(d.props.forEach(function(a){return g(b,a.name,a.shallow)}),d=d.end);return b}function c(d,u){for(var b=[],a=1;a<arguments.length;++a)b[a-1]=arguments[a];switch(d){case "alternation":var a=
$jscomp.makeIterator(b),b=a.next().value,C=a.next().value,x={type:S,next:null,prev:null},B={type:L,end:x,next:null,prev:null},a=function(){var a=[],b=[];C.forEach(function(d){if(d.first.type===L)for(var k=0;k<d.first.length;k++)b.push.apply(b,[].concat($jscomp.arrayFromIterable(a.first.next[k].props))),a.push({first:a.first.next[k].regexPart,last:a.last.prev[k].regexPart,matchable:!0});else a.push(d)});if(0<b.length){var d=c("quantifier",I,O,0,1,c("group",[]),!0);d.props=b;d.matchable=!1;a.push(d)}return a}(),
f=a.filter(function(a){return a.matchable}),D=[];a.forEach(function(a){return(a.props=p(a.first,a.last)).forEach(function(a){return g(D,a.name,a.shallow)})});f.forEach(function(a){return a.props=D.filter(function(b){return a.props.every(function(a){return a.name!==b.name})})});if(1===f.length&&0===f[0].props.length&&!b)return f[0];f.forEach(function(a){return a.first.prev=B,a.last.next=x});B.next=f.map(function(a){return{props:a.props,regexPart:a.first}});x.prev=f.map(function(a){return{props:a.props,
regexPart:a.last}});return{first:B,last:x,matchable:0!==f.length};case "assertion":var q=$jscomp.makeIterator(b),a=q.next().value,f=q.next().value,t=q.next().value,b=q.next().value,q=q.next().value,r={type:T,name:a,dimensions:f,condition:t,then:b.first,thenNot:q.first,prev:null},a={type:U,name:a,dimensions:f,condition:t,then:b.last,thenNot:q.last,next:null};b.first.prev=r;q.first.prev=r;b.last.next=a;q.last.next=a;return{first:r,last:a,matchable:b.matchable||q.matchable};case "backreference":return a=
$jscomp.makeIterator(b),b=a.next().value,a=a.next().value,b={type:V,name:b,dimensions:a,next:null,prev:null},{first:b,last:b,matchable:!0};case "captrGroup":a=$jscomp.makeIterator(b);b=a.next().value;f=a.next().value;a=a.next().value;f={type:K,name:b,objName:a.first.type===P?a.first.name:null,shallow:f,next:a.first,prev:null};t={type:W,next:null,prev:a.last};if("loc"===b||"input"===b||"name"===b)throw Error('Capturing group cannot be named "'+b+'".');a.first.prev=f;a.last.next=t;return{first:f,last:t,
matchable:a.matchable};case "group":return b=$jscomp.makeIterator(b).next().value,b={type:F,arr:b,next:null,prev:null},{first:b,last:b,matchable:!0};case "lookahead":t=$jscomp.makeIterator(b);b=t.next().value;a=t.next().value;f=t.next().value;t=t.next().value;q={type:Q,condition:b,negated:!1,lookbehind:t,next:null,prev:null};r={type:Q,condition:b,negated:!0,lookbehind:t,next:null,prev:null};if(t)return q.next=a.first,a.first.prev=q,r.next=f.first,f.first.prev=r,c("alternative",!1,!1,[{first:q,last:a.last,
matchable:b.matchable&&a.matchable},{first:r,last:f.last,matchable:f.matchable}]);a.last.next=q;q.prev=a.last;f.last.next=r;r.prev=f.last;return c("alternative",!1,!1,[{first:a.first,last:q,matchable:a.matchable&&b.matchable},{first:f.first,last:r,matchable:f.matchable}]);case "subroutine":return b=$jscomp.makeIterator(b).next().value,b={type:P,name:b,next:null,prev:null},{first:b,last:b,matchable:!0};case "quantifier":var r=$jscomp.makeIterator(b),q=r.next().value,a=r.next().value,f=r.next().value,
t=r.next().value,b=r.next().value,r=r.next().value,w=p(b.first,b.last),q={type:q,min:f,max:t,props:w,special:r,end:null,next:b.first,prev:null},a={type:a,min:f,max:t,props:w,special:r,start:q,next:null,prev:b.last};q.end=a;b.first.prev=q;b.last.next=a;return{first:q,last:a,matchable:b.matchable}}}function G(d){var u=d.toUpperCase()===d;switch(d){case "d":case "D":return{min:"0",max:"9",negated:u};case "w":return c("alternation",!1,[c("group",["_"]),c("group",[{min:"a",max:"z",negated:!1}]),c("group",
[{min:"A",max:"Z",negated:!1}]),c("group",[{min:"0",max:"9",negated:!1}])]);case "W":return["_",{min:"a",max:"z",negated:!1},{min:"A",max:"Z",negated:!1},{min:"0",max:"9",negated:!1}];case "s":return c("alternation",!1,[c("group",["\n"]),c("group",["\r"]),c("group",["\t"]),c("group",[" "]),c("group",["\u00a0"]),c("group",["\u1680"]),c("group",["\u180e"]),c("group",[{min:"\u8192",max:"\u8202",negated:!1}]),c("group",["\u2028"]),c("group",["\u2029"]),c("group",["\u202f"]),c("group",["\u205f"]),c("group",
["\u3000"]),c("group",["\ufeff"])]);case "S":return["\n","\r","\t","\u00a0","\u1680","\u180e",{min:"\u8192",max:"\u8202",negated:!1},"\u2028","\u2029","\u202f","\u205f","\u3000","\ufeff"];case "l":return c("alternation",!1,[c("group",["\n"]),c("group",["\r"]),c("group",["\u2028"]),c("group",["\u2029"])]);case "L":return["\n","\r","\t","\u2028","\u2029"];case "n":return"\n";case "N":return{min:"\n",max:"\n",negated:!0};case "r":return"\r";case "R":return{min:"\r",max:"\r",negated:!0};case "t":return"\t";
case "T":return{min:"\t",max:"\t",negated:!0};case "a":return X;case "z":return Y;case "`":return Z;case "'":return aa;default:return null}}0;var H="undefined"!==typeof window,J="object"!==typeof exports||"undefined"!==typeof window&&exports===window.exports?{}:exports;J["default"]=J;H&&(window.RegeRex=J);$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();
$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();var ba=Symbol("startLine"),ca=Symbol("endLine"),X=Symbol("startString"),Y=Symbol("endString"),Z=Symbol("startPosition"),aa=Symbol("endPosition"),da=Symbol("wordBoundary"),L=Symbol("alternationStart"),
S=Symbol("alternationEnd"),T=Symbol("assertionStart"),U=Symbol("assertionEnd"),V=Symbol("backreference"),K=Symbol("capturingGroupStart"),W=Symbol("capturingGroupEnd"),Q=Symbol("conditionCheck"),F=Symbol("group"),M=Symbol("greedyStart"),R=Symbol("greedyEnd"),N=Symbol("possesiveStart"),ea=Symbol("possesiveEnd"),I=Symbol("lazyStart"),O=Symbol("lazyEnd"),P=Symbol("subroutine"),fa=Symbol("quantifierBreak"),ga=Symbol("quantifierNested");G.l=new Set(["\n","\r","\u2028","\u2029"]);var ia=new Set("[]()^$|\\*+?{}".split("")),
H=function(d,c){c=void 0===c?!1:c;if("string"!==typeof d)throw Error("Name must be a string");this.regexMap=new Map;this.name=d;this.trackLines=!!c};H.prototype.add=function(d){"string"===typeof d&&(d=new ha(d));if(!(d instanceof ha))throw Error("Argument regex must be a string or an instance of Regex.");if(this.regexMap.has(d.name))throw Error('Regex "'+d.name+'" already exists.');this.regexMap.set(d.name,d);return this};H.prototype.match=function(d,c,b,a){function g(a){switch(a){case "subroutine":return 0===
u.length?null:u[u.length-1];case "quantifier":a=g("subroutine");if(null===a)return null;a=a.quantifierOpenStack;return 0===a.length?null:a[a.length-1];case "captrGroup":a=g("quantifier");if(null===a)return null;a=a.captrGroupOpenStack;return 0===a.length?null:a[a.length-1]}}function x(a,b){b=void 0===b?!1:b;switch(a){case "subroutine":if(b){var d=q.pop();return u.push(d),d}d=u.pop();return q.push(d),d;case "quantifier":d=g("subroutine");if(b){var c=d.quantifierClosedStack.pop();return d.quantifierOpenStack.push(c),
c}c=d.quantifierOpenStack.pop();return d.quantifierClosedStack.push(c),c;case "captrGroup":d=g("quantifier");if(b)return c=d.captrGroupClosedStack.pop(),d.captrGroupOpenStack.push(c),c;c=d.captrGroupOpenStack.pop();return d.captrGroupClosedStack.push(c),c}}function B(a,b){for(var d=[],c=1;c<arguments.length;++c)d[c-1]=arguments[c];switch(a){case "quantifier":c=g(a);if(0===d.length)return 0===c.end&&(g("subroutine").quantifierOpenStack.pop(),c=g(a)),c&&c.captrGroupClosedStack.pop(),c;c&&c.captrGroupClosedStack.push(c.start===
c.end?fa:ga);if(!c||c.start!==c.end){var e=$jscomp.makeIterator(d),c=e.next().value,d=e.next().value,h=e.next().value,e=e.next().value,k=g("subroutine");k.quantifierOpenStack.push(c={captrGroupOpenStack:[],captrGroupClosedStack:[],start:h,end:e,props:c,special:d,flag:!0,depth:k.quantifierOpenStack.length})}return c;case "captrGroup":c=g("quantifier");if(0===d.length)return c.captrGroupOpenStack.pop();k=$jscomp.makeIterator(d);d=k.next().value;h=k.next().value;e=k.next().value;k=k.next().value;d={name:d,
objName:h,shallow:e,posStart:k,posEnd:0};return c.captrGroupOpenStack.push(d),d}}function f(e,h,m,l){if(null===l){if(null===g("subroutine")){var k=function(a){var b=a.sub,d=a.children,c=[{props:[],qIndex:0}],e=0,h=0;b.quantifierClosedStack.forEach(function(a){function g(b,c){var d=f[b];switch(q[b]){case 0:a.special?f[b]=c:d.push(c);break;case 1:a.special?f[b]=[f[b],c]:d[d.length-1]=[d[d.length-1],c];break;default:a.special?d.push(c):d[d.length-1].push(c)}q[b]++}var f={},q={};a.props.forEach(function(c){if(c.shallow)return c.name in
b.retObj||(b.retObj[c.name]=[]);q[c.name]=0;f[c.name]=a.special?null:[]});a.captrGroupClosedStack.forEach(function(f){if(f===fa)return a.props.forEach(function(a){return q[a.name]=0});if(f===ga){var n=c[e].props[c[e].qIndex++];return Object.keys(n).forEach(function(a){return g(a,n[a])})}var m=f.name,l=f.objName,r=f.shallow,u=f.posStart;f=f.posEnd;if(null===l)l=w.substring(u,f);else{for(;d[h].sub.retObj.name!==l;)h++;l=k(d[h++])}if(r)return m in b.retObj?b.retObj[m].push(l):b.retObj[m]=[l];g(m,l)});
if(e===a.depth)c[e].props.push(f);else if(e>a.depth)c[e]={props:[],qIndex:0},c[a.depth].props.push(f);else if(e<a.depth){for(;c.length<=a.depth;)c.push({props:[],qIndex:0});c[a.depth].props.push(f)}e=a.depth});return Object.assign(c[0].props[0],b.retObj)},E=[[]],p=0;q.forEach(function(a){if(a.depth===p)E[p].push({sub:a,children:[]});else if(a.depth<p)E[a.depth].push({sub:a,children:E[p]}),E[p]=[];else{for(;E.length<=a.depth;)E.push([]);E[a.depth].push({sub:a,children:[]})}p=a.depth});return k(E[0][0])}var n=
x("subroutine"),v=n.retObj,y=n.next,D=g("subroutine"),n=d,v=v.loc.end;v.pos=(a&&(v.line=h,v.column=m),e);d=D&&D.ignoreCase?r:w;v=f(e,h,m,y);return v||(x("subroutine",!0),d=n),v}l.type===U&&(l=l.next);switch(l.type){case T:throw Error("Not implemented yet, see issue #1.");case L:for(n=0;n<l.next.length;n++){B("quantifier",l.next[n].props,!0,1,0);if(v=f(e,h,m,l.next[n].regexPart))return v;B("quantifier")}return null;case S:return x("quantifier"),n=f(e,h,m,l.next),n||x("quantifier",!0),n;case V:throw Error("Not implemented yet, see issue # 2.");
case K:return B("captrGroup",l.name,l.objName,l.shallow,e),n=f(e,h,m,l.next),n||B("captrGroup"),n;case W:return x("captrGroup").posEnd=e,n=f(e,h,m,l.next),n||x("captrGroup",!0),n;case Q:return n=condition.lookbehind?f(e,h,m,l.condition):matchBackwards(e,h,m,l.condition),(l.negated?!n:n)?f(e,h,m,l.next):null;case M:case N:case I:var n=function(){if((l.type!==N||C.flag)&&C.start>=l.min){C.flag=!1;x("quantifier");var a=f(e,h,m,l.end.next);return a||x("quantifier",!0),a}return null},v=function(){if(C.start<
l.max){C.start++;var a=f(e,h,m,l.next);return a||C.start--,a}return null},C=B("quantifier",l.props,l.special,0,0),n=l.type===I?n()||v():v()||n();return n||B("quantifier"),n;case R:case ea:case O:return n=g("quantifier"),n.end++,v=f(e,h,m,l.start),v||n.end--,v;case F:var z,A=0<e?d.charAt(e-1):null;return l.arr.every(function(a){z=A;A=d.charAt(e++);if("symbol"===typeof a){var f;switch(a){case ba:f=G.l.has(z);break;case ca:f=G.l.has(A);break;case X:f=1===e;break;case Y:f=e===d.length;break;case Z:f=
e===c+1;break;case aa:f=e===b;break;case da:throw Error("Not implemented yet, see issue #3.");}return f?(e--,A=z,!0):!1}if(e>b)return!1;G.l.has(A)?(h++,m=0):m++;return"object"===typeof a?(f=a.min<=A&&A<=a.max,a.negated?!f:f):a instanceof Array?a.every(function(a){if("string"===typeof a)return a!==A;var b=A<a.min||A>a.max;return a.negated?!b:b}):A===a})?f(e,h,m,l.next):null;case P:return n=t.get(l.name),v={retObj:{input:w,loc:{start:{pos:null,line:null,column:null},end:{pos:null,line:null,column:null}},
name:n.name},quantifierOpenStack:[],quantifierClosedStack:[],ignoreCase:n.ignoreCase,next:l.next,depth:u.length},u.push(v),v=v.retObj.loc.start,v.pos=(a&&(v.line=h,v.column=m),e),n.ignoreCase&&null===r&&(r=d.toLowerCase()),d=n.ignoreCase?r:w,n=f(e,h,m,n.parsed.first),n||u.pop(),n}}c=void 0===c?0:c;b=void 0===b?d.length:b;a=void 0===a?this.trackLines:a;2===arguments.length&&"boolean"===typeof c&&(a=c,c=0);3===arguments.length&&"boolean"===typeof b&&(a=b,b=d.length);if("string"!==typeof d)throw Error("Parameter 'str' must be a string.");
if("number"!==typeof c||0!==c%1||0>c)throw Error("Invalid parameter 'start'.");if("number"!==typeof b||0!==b%1)throw Error("Invalid parameter 'start'.");if(c>d.length)return null;b>d.length&&(b=d.length);a=!!a;var u=[],q=[],t=this.regexMap,r=null,w=d,p=0,y=0;if(!this.regexMap.has(this.name))throw Error("Default regex is required to start matching");if(a)for(var e=0;e<c;e++)y++,G.l.has(d.charAt(e))&&(y=0,p++);for(;c<b;){if(e=f(c,p,y,this.regexMap.get(this.name).parsed.subroutine))return e;y++;G.l.has(d.charAt(c++))&&
(y=0,p++)}return null};H.prototype.replace=function(c,g,b,a){throw Error("Not implemented yet.");};H.prototype.matchAll=function(c,g,b,a){function d(d,t){for(;;)switch(u){case 0:a=void 0===a?f.trackLines:a,p=null;case 1:if(!(p=f.match(c,g,b,a))){u=2;break}u=3;return{value:p,done:!1};case 3:if(void 0===t){u=4;break}u=-1;throw t;case 4:g=p.loc.end.pos;u=1;break;case 2:return u=-1,{value:p,done:!0};default:return{value:void 0,done:!0}}}var u=0,p,f=this,D={next:function(a){return d(a,void 0)},"throw":function(a){return d(void 0,
a)},"return":function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();D[Symbol.iterator]=function(){return this};return D};J.RegexGroup=H;var ha=J.Regex=function(d){function g(p,f){function u(c){for(var e="";(a=d.charAt(b++)).match(/[A-Za-z_]/);)e+=a;if(!c.includes(a)||""===e)throw Error(""===a?"Unexpected end of string.":b-1+": Invalid character:"+a);return e}function q(c){var e=null,f=!1;"-"===d.charAt(b)&&(f=!0,b++);for(;(a=d.charAt(b++)).match(/\d/);)e=null===e?+a:+a+10*
e;if(!c.includes(a)||f&&null===e)throw Error(""===a?"Unexpected end of string.":b-1+": Invalid character:"+a);if(f&&0===e)throw Error("Zero cannot be negative");return f?-1*e:e}f=void 0===f?!1:f;for(var t=new Map,r=null,w=null,z=!0,y={};a=d.charAt(b++);){var e=void 0;switch(a){case "^":e=ba;break;case "$":e=ca;break;case "|":e=da;break;case "\\":a=d.charAt(b++);if(""===a)throw Error("Unexpected end of string.");if(e=G(a)||(ia.has(a)||p.includes(a))&&(e=a))break;switch(a){case "u":e=d.substring(b,
b+3).match(/\{([0-9a-f]{4,5})\}/);if(!e)throw Error(b+": Invalid escape sequance.");e=String.fromCharCode(parseInt(e[1],16));break;default:throw Error(b-1+": Unknown escape character: "+a);}break;case ")":case "]":case "}":case ":":case "<":case ">":if(p.includes(a))return r||(r=w={type:F,arr:[],next:null,prev:null}),{first:r,last:w,matchable:z};if(")]}".includes(a))throw Error(b-1+": Unmatched brace/bracket/parenthesis.");e=a;break;case "*":case "+":case "?":case "{":throw Error(b-1+"Unescaped special character: "+
a);default:e=x?a.toLowerCase():a;break;case "(":a=d.charAt(b++);if(!a)throw Error("Unexpected end of string.");switch(a){default:b--;e=g(")");break;case "=":for(var k=u(")["),e=[];"["===a;){var h=q("]");a=d.charAt(b++);e.push(h)}if(")"!==a)throw Error(b-1+": Invalid character: "+a);e=c("backreference",k,e);break;case ":":k=u(":.)");h="."===a;if(e=")"===a)e=c("subroutine",k);else{if(t.has(k)){if(t.get(k)!==h)throw Error("Capturing groups with the same name cannot be both shallow and normal");}else t.set(k,
h);e=c("captrGroup",k,h,g(")"))}break;case "?":var k=g(":>"),e=void 0,m=!1;">"===a?(e=k.last,k=g(":"),h=g(")"),m=!0):(h=g("<"),e=g(")").first);e=c("lookahead",e,k,h,m);break;case "|":m=u("[=>");for(e=[];"["===a;){k=q("]");if(null===k)throw Error(b-1+"Invalid character: ]");e.push(k);a=d.charAt(b++)}var l="="===a?g(">").first:null,k=g(":"),h=g(")"),e=c("assertion",m,e,l,k,h)}break;case "[":if(e=d.substring(b,b+5).match(/^(\^?)-([^]?)([^]?)([^]?)/)){m=$jscomp.makeIterator(e);m.next();k=m.next().value;
e=m.next().value;h=m.next().value;m=m.next().value;if(""===m)throw Error("Unexpected end of string.");if("]"!==m)throw Error(b+(k?4:3)+": Unexpected character: "+m);e!==h&&(e>h&&(h=$jscomp.makeIterator([h,e]),e=h.next().value,h=h.next().value),e={min:e,max:h,negated:!!k},b+=k?5:4)}else{e="^"===d.charAt(b)&&(b++,!0);k=[];y.set=e&&new Set;for(h=void 0;h=g("]",!0),h.first.type!==F||0!==h.first.arr.length;)if(e){if(h.first.type!==F||h.first.arr.some(function(a){return function(b){a.set.add(b);return"symbol"===
typeof b}}(y)))throw Error(b-1+": Negated alternation can only contain characters, character classes and negated alternations.");}else k.push(h);e=e?Array.from(y.set):c("alternation",w&&w.type===K,k)}}a=d.charAt(b++);h=void 0;k=!1;switch(a){default:b--;break;case "?":h=[0,1];k=!0;break;case "*":h=[0,Infinity];break;case "+":h=[1,Infinity];break;case "{":h=q("},");if(!h)throw Error(b-1+": Empty quantifier: {}");h=[h,","===a?q("}"):h];null===h[1]&&(h[1]=Infinity);if(0<h.length&&(0>h[0]||h[1]<h[0]))throw Error(b-
1+": Quantifier with negative or swapped boundaries.");}if(h){a=d.charAt(b++);m=void 0;switch(a){default:b--;m=M;l=R;break;case "+":m=N;l=ea;break;case "?":m=I,l=O}if(!z)continue;"object"===typeof e&&"first"in e||(e=c("group",[e]));if(!e.matchable){0!==h[0]&&(z=c("alternation",!1,[]),r=z.first,w=z.last,z=z.matchable);continue}e=c.apply(null,[].concat(["quantifier",m,l],$jscomp.arrayFromIterable(h),[e,k]))}if("object"!==typeof e||!("first"in e))if(w&&w.type===F){w.arr.push(e);continue}else e=c("group",
[e]);if(f)return e;(e.first.prev=w)&&(w.next=e.first);r||(r=e.first);w=e.last;y={set:y.set}}if(p)throw Error('Unexpected end of string; expected one of: "'+p+'".');r||(r=w={type:F,arr:[],next:null,prev:null});return{first:r,last:w,matchable:z,subroutine:null}}var b=0,a,p=d.indexOf(":");if(-1===p)throw Error("Regexp must contain a colon.");var x=this.ignoreCase=!("i|"!==d.substring(0,2)||!(b+=2));this.name=d.substring(b,p);b=p+1;this.ignoreCase&&(d=d.toLowerCase());this.parsed=c("quantifier",M,R,1,
1,g(""),!0);this.parsed.subroutine=c("subroutine",this.name).first}})();