'use strict';var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(e,p,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");e!=Array.prototype&&e!=Object.prototype&&(e[p]=d.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.iterator;e||(e=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[e]&&$jscomp.defineProperty(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(e){var p=0;return $jscomp.iteratorPrototype(function(){return p<e.length?{done:!1,value:e[p++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(e){$jscomp.initSymbolIterator();e={next:e};e[$jscomp.global.Symbol.iterator]=function(){return this};return e};$jscomp.makeIterator=function(e){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var p=e[Symbol.iterator];return p?p.call(e):$jscomp.arrayIterator(e)};$jscomp.arrayFromIterator=function(e){for(var p,d=[];!(p=e.next()).done;)d.push(p.value);return d};$jscomp.arrayFromIterable=function(e){return e instanceof Array?e:$jscomp.arrayFromIterator($jscomp.makeIterator(e))};
(function(){function e(c,d,a){c.every(function(a){return a.name!==d})&&c.push({name:d,shallow:a})}function p(c,d){for(var a=[];c!==d;)c.type===I&&e(a,c.name,c.shallow),c.type===J?(c.next.forEach(function(b){return b.props.forEach(function(b){return e(a,b.name,b.shallow)})}),c=c.end):c.type!==L&&c.type!==M&&c.type!==G||!c.props?c=c.next:(c.props.forEach(function(b){return e(a,b.name,b.shallow)}),c=c.end);return a}function d(c,C){for(var a=[],b=1;b<arguments.length;++b)a[b-1]=arguments[b];switch(c){case "alternation":var b=
$jscomp.makeIterator(a),a=b.next().value,K=b.next().value,w={type:R,next:null,prev:null},B={type:J,end:w,next:null,prev:null},b=function(){var a=[],b=[];K.forEach(function(h){if(h.first.type===J)for(var g=0;g<h.first.length;g++)b.push.apply(b,[].concat($jscomp.arrayFromIterable(a.first.next[g].props))),a.push({first:a.first.next[g].regexPart,last:a.last.prev[g].regexPart,matchable:!0});else a.push(h)});if(0<b.length){var c=d("quantifier",G,N,0,1,d("group",[]),!0);c.props=b;c.matchable=!1;a.push(c)}return a}(),
k=b.filter(function(a){return a.matchable}),S=[];b.forEach(function(a){return(a.props=p(a.first,a.last)).forEach(function(a){return e(S,a.name,a.shallow)})});k.forEach(function(a){return a.props=S.filter(function(b){return a.props.every(function(a){return a.name!==b.name})})});if(1===k.length&&0===k[0].props.length&&!a)return k[0];k.forEach(function(a){return a.first.prev=B,a.last.next=w});B.next=k.map(function(a){return{props:a.props,regexPart:a.first}});w.prev=k.map(function(a){return{props:a.props,
regexPart:a.last}});return{first:B,last:w,matchable:0!==k.length};case "assertion":var q=$jscomp.makeIterator(a),b=q.next().value,k=q.next().value,v=q.next().value,a=q.next().value,q=q.next().value,l={type:T,name:b,dimensions:k,condition:v,then:a.first,thenNot:q.first,prev:null},b={type:U,name:b,dimensions:k,condition:v,then:a.last,thenNot:q.last,next:null};a.first.prev=l;q.first.prev=l;a.last.next=b;q.last.next=b;return{first:l,last:b,matchable:a.matchable||q.matchable};case "backreference":return b=
$jscomp.makeIterator(a),a=b.next().value,b=b.next().value,a={type:V,name:a,dimensions:b,next:null,prev:null},{first:a,last:a,matchable:!0};case "captrGroup":return a=$jscomp.makeIterator(a),b=a.next().value,k=a.next().value,a=a.next().value,b={type:I,name:b,objName:a.first.type===O?a.first.name:null,shallow:k,next:a.first,prev:null},k={type:W,next:null,prev:a.last},a.first.prev=b,a.last.next=k,{first:b,last:k,matchable:a.matchable};case "group":return a=$jscomp.makeIterator(a).next().value,a={type:E,
arr:a,next:null,prev:null},{first:a,last:a,matchable:!0};case "lookahead":v=$jscomp.makeIterator(a);a=v.next().value;b=v.next().value;k=v.next().value;v=v.next().value;q={type:P,condition:a,negated:!1,lookbehind:v,next:null,prev:null};l={type:P,condition:a,negated:!0,lookbehind:v,next:null,prev:null};if(v)return q.next=b.first,b.first.prev=q,l.next=k.first,k.first.prev=l,d("alternative",!1,!1,[{first:q,last:b.last,matchable:a.matchable&&b.matchable},{first:l,last:k.last,matchable:k.matchable}]);b.last.next=
q;q.prev=b.last;k.last.next=l;l.prev=k.last;return d("alternative",!1,!1,[{first:b.first,last:q,matchable:b.matchable&&a.matchable},{first:k.first,last:l,matchable:k.matchable}]);case "subroutine":return a=$jscomp.makeIterator(a).next().value,a={type:O,name:a,next:null,prev:null},{first:a,last:a,matchable:!0};case "quantifier":var l=$jscomp.makeIterator(a),q=l.next().value,b=l.next().value,k=l.next().value,v=l.next().value,a=l.next().value,l=l.next().value,u=p(a.first,a.last),q={type:q,min:k,max:v,
props:u,special:l,end:null,next:a.first,prev:null},b={type:b,min:k,max:v,props:u,special:l,start:q,next:null,prev:a.last};q.end=b;a.first.prev=q;a.last.next=b;return{first:q,last:b,matchable:a.matchable}}}function F(c){c.toUpperCase();switch(c){case "d":case "D":return{min:"0",max:"9",negated:uppercase};case "w":return d("alternation",!1,[d("group",["_"]),d("group",[{min:"a",max:"z",negated:!1}]),d("group",[{min:"A",max:"Z",negated:!1}]),d("group",[{min:"0",max:"9",negated:!1}])]);case "W":return["_",
{min:"a",max:"z",negated:!1},{min:"A",max:"Z",negated:!1},{min:"0",max:"9",negated:!1}];case "s":return d("alternation",!1,[d("group",["\n"]),d("group",["\r"]),d("group",["\t"]),d("group",[" "]),d("group",["\u00a0"]),d("group",["\u1680"]),d("group",["\u180e"]),d("group",[{min:"\u8192",max:"\u8202",negated:!1}]),d("group",["\u2028"]),d("group",["\u2029"]),d("group",["\u202f"]),d("group",["\u205f"]),d("group",["\u3000"]),d("group",["\ufeff"])]);case "S":return["\n","\r","\t","\u00a0","\u1680","\u180e",
{min:"\u8192",max:"\u8202",negated:!1},"\u2028","\u2029","\u202f","\u205f","\u3000","\ufeff"];case "l":return d("alternation",!1,[d("group",["\n"]),d("group",["\r"]),d("group",["\u2028"]),d("group",["\u2029"])]);case "L":return["\n","\r","\t","\u2028","\u2029"];case "n":return"\n";case "N":return{min:"\n",max:"\n",negated:!0};case "r":return"\r";case "R":return{min:"\r",max:"\r",negated:!0};case "t":return"\t";case "T":return{min:"\t",max:"\t",negated:!0};case "a":return X;case "z":return Y;case "`":return Z;
case "'":return aa;default:return null}}0;var y="undefined"!==typeof window,H="object"!==typeof exports||"undefined"!==typeof window&&exports===window.exports?{}:exports;H.default=H;y&&(window.RegeRex=H);$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();
$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();var ba=Symbol("startLine"),ca=Symbol("endLine"),X=Symbol("startString"),Y=Symbol("endString"),Z=Symbol("startPosition"),aa=Symbol("endPosition"),da=Symbol("wordBoundary"),J=Symbol("alternationStart"),R=Symbol("alternationEnd"),T=Symbol("assertionStart"),U=Symbol("assertionEnd"),V=Symbol("backreference"),
I=Symbol("capturingGroupStart"),W=Symbol("capturingGroupEnd"),P=Symbol("conditionCheck"),E=Symbol("group"),L=Symbol("greedyStart"),Q=Symbol("greedyEnd"),M=Symbol("possesiveStart"),ea=Symbol("possesiveEnd"),G=Symbol("lazyStart"),N=Symbol("lazyEnd"),O=Symbol("subroutine"),fa=Symbol("quantifierBreak"),ga=Symbol("quantifierNested");F.l=new Set(["\n","\r","\u2028","\u2029"]);var ia=new Set("[]()^$|\\*+?{}".split("")),y=function(c,d){d=void 0===d?!1:d;if("string"!==typeof c)throw Error("Name must be a string");
this.regexMap=new Map;this.name=c;this.trackLines=!!d};y.prototype.add=function(c){"string"===typeof c&&(c=new ha(c));if(!(c instanceof ha))throw Error("Argument regex must be a string or an instance of Regex.");if(this.regexMap.has(c.name))throw Error('Regex "'+c.name+'" already exists.');this.regexMap.set(c.name,c);return this};y.prototype.match=function(c,d,a,b){function e(a){switch(a){case "subroutine":return 0===C.length?null:C[C.length-1];case "quantifier":a=e("subroutine");if(null===a)return null;
a=a.quantifierOpenStack;return 0===a.length?null:a[a.length-1];case "captrGroup":a=e("quantifier");if(null===a)return null;a=a.captrGroupOpenStack;return 0===a.length?null:a[a.length-1]}}function w(a,b){b=void 0===b?!1:b;switch(a){case "subroutine":if(b)return b=q.pop(),C.push(b),b;b=C.pop();return q.push(b),b;case "quantifier":a=e("subroutine");if(b)return b=a.quantifierClosedStack.pop(),a.quantifierOpenStack.push(b),b;b=a.quantifierOpenStack.pop();return a.quantifierClosedStack.push(b),b;case "captrGroup":a=
e("quantifier");if(b)return b=a.captrGroupClosedStack.pop(),a.captrGroupOpenStack.push(b),b;b=a.captrGroupOpenStack.pop();return a.captrGroupClosedStack.push(b),b}}function B(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];switch(a){case "quantifier":d=e(a);if(0===c.length)return 0===d.end&&(e("subroutine").quantifierOpenStack.pop(),d=e(a)),d&&d.captrGroupClosedStack.pop(),d;d&&d.captrGroupClosedStack.push(d.start===d.end?fa:ga);if(!d||d.start!==d.end){var g=$jscomp.makeIterator(c),
d=g.next().value,c=g.next().value,f=g.next().value,g=g.next().value,h=e("subroutine");h.quantifierOpenStack.push(d={captrGroupOpenStack:[],captrGroupClosedStack:[],start:f,end:g,props:d,special:c,flag:!0,depth:h.quantifierOpenStack.length})}return d;case "captrGroup":d=e("quantifier");if(0===c.length)return d.captrGroupOpenStack.pop();h=$jscomp.makeIterator(c);c=h.next().value;f=h.next().value;g=h.next().value;h=h.next().value;c={name:c,objName:f,shallow:g,posStart:h,posEnd:0};return d.captrGroupOpenStack.push(c),
c}}function k(h,g,f,m){if(null===m){if(null===e("subroutine")){var t=function(a){var b=a.sub,d=a.children,c=[{props:[],qIndex:0}],f=0,g=0;b.quantifierClosedStack.forEach(function(a){function h(b,c){var d=e[b];switch(k[b]){case 0:a.special?e[b]=c:d.push(c);break;case 1:a.special?e[b]=[e[b],c]:d[d.length-1]=[d[d.length-1],c];break;default:a.special?d.push(c):d[d.length-1].push(c)}k[b]++}var e={},k={};a.props.forEach(function(c){if(c.shallow)return c.name in b.retObj||(b.retObj[c.name]=[]);k[c.name]=
0;e[c.name]=a.special?null:[]});a.captrGroupClosedStack.forEach(function(e){if(e===fa)return a.props.forEach(function(a){return k[a.name]=0});if(e===ga){var n=c[f].props[c[f].qIndex++];return Object.keys(n).forEach(function(a){return h(a,n[a])})}var m=e.name,l=e.objName,q=e.shallow,ja=e.posStart;e=e.posEnd;if(null===l)l=u.substring(ja,e);else{for(;d[g].sub.retObj.name!==l;)g++;l=t(d[g++])}if(q)return m in b.retObj?b.retObj[m].push(l):b.retObj[m]=[l];h(m,l)});if(f===a.depth)c[f].props.push(e);else if(f>
a.depth)c[f]={props:[],qIndex:0},c[a.depth].props.push(e);else if(f<a.depth){for(;c.length<=a.depth;)c.push({props:[],qIndex:0});c[a.depth].props.push(e)}f=a.depth});return Object.assign(c[0].props[0],b.retObj)},D=[[]],p=0;q.forEach(function(a){if(a.depth===p)D[p].push({sub:a,children:[]});else if(a.depth<p)D[a.depth].push({sub:a,children:D[p]}),D[p]=[];else{for(;D.length<=a.depth;)D.push([]);D[a.depth].push({sub:a,children:[]})}p=a.depth});return t(D[0][0])}var n=w("subroutine"),r=n.retObj,z=n.next,
K=e("subroutine"),n=c,r=r.loc.end;r.pos=(b&&(r.line=g,r.column=f),h);c=K&&K.ignoreCase?l:u;r=k(h,g,f,z);return r||(w("subroutine",!0),c=n),r}m.type===U&&(m=m.next);switch(m.type){case T:throw Error("Not implemented yet.");case J:for(n=0;n<m.next.length;n++){B("quantifier",m.next[n].props,!0,1,0);if(r=k(h,g,f,m.next[n].regexPart))return r;B("quantifier")}return null;case R:return w("quantifier"),n=k(h,g,f,m.next),n||w("quantifier",!0),n;case V:throw Error("Not implemented yet.");case I:return B("captrGroup",
m.name,m.objName,m.shallow,h),n=k(h,g,f,m.next),n||B("captrGroup"),n;case W:return w("captrGroup").posEnd=h,n=k(h,g,f,m.next),n||w("captrGroup",!0),n;case P:return n=condition.lookbehind?k(h,g,f,m.condition):matchBackwards(h,g,f,m.condition),(m.negated?!n:n)?k(h,g,f,m.next):null;case L:case M:case G:var n=function(){if((m.type!==M||x.flag)&&x.start>=m.min){x.flag=!1;w("quantifier");var a=k(h,g,f,m.end.next);return a||w("quantifier",!0),a}return null},r=function(){if(x.start<m.max){x.start++;var a=
k(h,g,f,m.next);return a||x.start--,a}return null},x=B("quantifier",m.props,m.special,0,0),n=m.type===G?n()||r():r()||n();return n||B("quantifier"),n;case Q:case ea:case N:return n=e("quantifier"),n.end++,r=k(h,g,f,m.start),r||n.end--,r;case E:var y,A=0<h?c.charAt(h-1):null;return m.arr.every(function(b){y=A;A=c.charAt(h++);if("symbol"===typeof b){var e;switch(b){case ba:e=F.l.has(y);break;case ca:e=F.l.has(A);break;case X:e=1===h;break;case Y:e=h===c.length;break;case Z:e=h===d+1;break;case aa:e=
h===a;break;case da:throw Error("Not yet implemented.");}return e?(h--,A=y,!0):!1}if(h>a)return!1;F.l.has(A)?(g++,f=0):f++;return"object"===typeof b?(e=b.min<=A&&A<=b.max,b.negated?!e:e):b instanceof Array?b.every(function(a){if("string"===typeof a)return a!==A;var b=A<a.min||A>a.max;return a.negated?!b:b}):A===b})?k(h,g,f,m.next):null;case O:return n=v.get(m.name),r={retObj:{input:u,loc:{start:{pos:null,line:null,column:null},end:{pos:null,line:null,column:null}},name:n.name},quantifierOpenStack:[],
quantifierClosedStack:[],ignoreCase:n.ignoreCase,next:m.next,depth:C.length},C.push(r),r=r.retObj.loc.start,r.pos=(b&&(r.line=g,r.column=f),h),n.ignoreCase&&null===l&&(l=c.toLowerCase()),c=n.ignoreCase?l:u,n=k(h,g,f,n.parsed.first),n||C.pop(),n}}d=void 0===d?0:d;a=void 0===a?c.length:a;b=void 0===b?this.trackLines:b;2===arguments.length&&"boolean"===typeof d&&(b=d,d=0);3===arguments.length&&"boolean"===typeof a&&(b=a,a=c.length);if("string"!==typeof c)throw Error("Parameter 'str' must be a string.");
if("number"!==typeof d||0!==d%1||0>d)throw Error("Invalid parameter 'start'.");if("number"!==typeof a||0!==a%1)throw Error("Invalid parameter 'start'.");if(d>c.length)return null;a>c.length&&(a=c.length);b=!!b;var C=[],q=[],v=this.regexMap,l=null,u=c,p=0,z=0;if(!this.regexMap.has(this.name))throw Error("Default regex is required to start matching");if(b)for(var f=0;f<d;f++)z++,F.l.has(c.charAt(f))&&(z=0,p++);for(;d<a;){if(f=k(d,p,z,this.regexMap.get(this.name).parsed.subroutine))return f;z++;F.l.has(c.charAt(d++))&&
(z=0,p++)}return null};y.prototype.replace=function(c,d,a,b){throw Error("Not implemented yet.");};y.prototype.matchAll=function(c,d,a,b){function e(a,b){for(;;)switch(p){case 0:throw p=-1,Error("Not implemented yet.");default:return{value:void 0,done:!0}}}var p=0;c={next:function(a){return e(a,void 0)},throw:function(a){return e(void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();c[Symbol.iterator]=function(){return this};return c};H.RegexGroup=y;var ha=
H.Regex=function(c){function e(p,k){function y(d){for(var e="";(b=c.charAt(a++)).match(/[A-Za-z_]/);)e+=b;if(!d.includes(b)||""===e)throw Error(""===b?"Unexpected end of string.":a-1+": Invalid character:"+b);return e}function q(d){var e=null,f=!1;"-"===c.charAt(a)&&(f=!0,a++);for(;(b=c.charAt(a++)).match(/\d/);)e=null===e?+b:+b+10*e;if(!d.includes(b)||f&&null===e)throw Error(""===b?"Unexpected end of string.":a-1+": Invalid character:"+b);if(f&&0===e)throw Error("Zero cannot be negative");return f?
-1*e:e}k=void 0===k?!1:k;for(var v=new Map,l=null,u=null,x=!0,z={};b=c.charAt(a++);){var f=void 0;switch(b){case "^":f=ba;break;case "$":f=ca;break;case "|":f=da;break;case "\\":b=c.charAt(a++);if(""===b)throw Error("Unexpected end of string.");if(f=F(b)||(ia.has(b)||p.includes(b))&&(f=b))break;switch(b){case "c":case "u":case "p":case "x":throw Error(a-1+": Not yet implemented.");default:throw Error(a-1+": Unknown escape character: "+b);}case ")":case "]":case "}":case ":":case "<":case ">":if(p.includes(b))return l||
(l=u={type:E,arr:[],next:null,prev:null}),{first:l,last:u,matchable:x};if(")]}".includes(b))throw Error(a-1+": Unmatched brace/bracket/parenthesis.");f=b;break;case "*":case "+":case "?":case "{":throw Error(a-1+"Unescaped special character: "+b);default:f=w?b.toLowerCase():b;break;case "(":b=c.charAt(a++);if(!b)throw Error("Unexpected end of string.");switch(b){default:a--;f=e(")");break;case "=":for(var h=y(")["),f=[];"["===b;){var g=q("]");b=c.charAt(a++);f.push(g)}if(")"!==b)throw Error(a-1+": Invalid character: "+
b);f=d("backreference",h,f);break;case ":":h=y(":.)");g="."===b;if(f=")"===b)f=d("subroutine",h);else{if(v.has(h)){if(v.get(h)!==g)throw Error("Capturing groups with the same name cannot be both shallow and normal");}else v.set(h,g);f=d("captrGroup",h,g,e(")"))}break;case "?":var h=e(":>"),f=void 0,t=!1;">"===b?(f=h.last,h=e(":"),g=e(")"),t=!0):(g=e("<"),f=e(")").first);f=d("lookahead",f,h,g,t);break;case "|":t=y("[=>");for(f=[];"["===b;){h=q("]");if(null===h)throw Error(a-1+"Invalid character: ]");
f.push(h);b=c.charAt(a++)}var m="="===b?e(">").first:null,h=e(":"),g=e(")"),f=d("assertion",t,f,m,h,g)}break;case "[":if(f=c.substring(a,a+5).match(/^(\^?)-([^]?)([^]?)([^]?)/)){t=$jscomp.makeIterator(f);t.next();h=t.next().value;f=t.next().value;g=t.next().value;t=t.next().value;if(""===t)throw Error("Unexpected end of string.");if("]"!==t)throw Error(a+(h?4:3)+": Unexpected character: "+t);f!==g&&(f>g&&(g=$jscomp.makeIterator([g,f]),f=g.next().value,g=g.next().value),f={min:f,max:g,negated:!!h},
a+=h?5:4)}else{f="^"===c.charAt(a)&&(a++,!0);h=[];z.set=f&&new Set;for(g=void 0;g=e("]",!0),g.first.type!==E||0!==g.first.arr.length;)if(f){if(g.first.type!==E||g.first.arr.some(function(a){return function(b){a.set.add(b);return"symbol"===typeof b}}(z)))throw Error(a-1+": Negated alternation can only contain characters, character classes and negated alternations.");}else h.push(g);f=f?Array.from(z.set):d("alternation",u&&u.type===I,h)}}b=c.charAt(a++);g=void 0;h=!1;switch(b){default:a--;break;case "?":g=
[0,1];h=!0;break;case "*":g=[0,Infinity];break;case "+":g=[1,Infinity];break;case "{":g=q("},");if(!g)throw Error(a-1+": Empty quantifier: {}");g=[g,","===b?q("}"):g];null===g[1]&&(g[1]=Infinity);if(0<g.length&&(0>g[0]||g[1]<g[0]))throw Error(a-1+": Quantifier with negative or swapped boundaries.");}if(g){b=c.charAt(a++);t=void 0;switch(b){default:a--;t=L;m=Q;break;case "+":t=M;m=ea;break;case "?":t=G,m=N}if(!x)continue;"object"===typeof f&&"first"in f||(f=d("group",[f]));if(!f.matchable){0!==g[0]&&
(x=d("alternation",!1,[]),l=x.first,u=x.last,x=x.matchable);continue}f=d.apply(null,[].concat(["quantifier",t,m],$jscomp.arrayFromIterable(g),[f,h]))}if("object"!==typeof f||!("first"in f))if(u&&u.type===E){u.arr.push(f);continue}else f=d("group",[f]);if(k)return f;(f.first.prev=u)&&(u.next=f.first);l||(l=f.first);u=f.last;z={set:z.set}}if(p)throw Error('Unexpected end of string; expected one of: "'+p+'".');l||(l=u={type:E,arr:[],next:null,prev:null});return{first:l,last:u,matchable:x,subroutine:null}}
var a=0,b,p=c.indexOf(":");if(-1===p)throw Error("Regexp must contain a colon.");var w=this.ignoreCase=!("i|"!==c.substring(0,2)||!(a+=2));this.name=c.substring(a,p);a=p+1;this.ignoreCase&&(c=c.toLowerCase());this.parsed=d("quantifier",L,Q,1,1,e(""),!0);this.parsed.subroutine=d("subroutine",this.name).first}})();